updated contract to 1.4.1 and rust 1.57, added locked contract
casper-ecosystem/contract-upgrade-example pull request #5
Opened 2021-10-25 11:43 UTC by deuszex

Updated casper and rust version.
Added a new contract to demonstrate locking contracts.
Added some details about upgrading contract.

2021-11-15 13:13 UTC, cspramit commented
@ramujin pls review

2021-11-16 05:54 UTC, ramujin commented
I am not sure why this was assigned to me as it is @deuszex's PR request. I'm moving myself to reviewer and placing him as the assignee.

@deuszex I noticed that you have hardcoded a Linux dependency in the Makefile that breaks the code for me on my Mac. Line 2 of the Makefile reads `rustup default nightly-2021-09-17-x86_64-unknown-linux-gnu`. If you want to ensure the nightly build is updated, you can issue commands similar to what we have in the Counter docs: https://casper.network/docs/dapp-dev-guide/tutorials/counter/setup.

I'm happy to test and review once it's ready :)

2021-11-19 01:02 UTC, ramujin requested changes

2021-11-19 01:02 UTC, ramujin commented on Makefile
> +	rustup default nightly-2021-09-17-x86_64-unknown-linux-gnu
This line breaks Rust the installation on a Mac. After running the make commands, I had to reinstall Rust from scratch in order to get NCTL to work again.

2022-06-06 14:56 UTC, devendran-m commented
Closing as won't do

2022-06-06 14:56 UTC, closed without merging